journal/about/urls.py
from django.urls import path

from about import views
from about.apps import AboutConfig

app_name = AboutConfig.name

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
    path('skill/', views.AboutSkillView.as_view(), name='skill'),
]

journal/journal/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from about.apps import AboutConfig
from posts.apps import PostsConfig
from users.apps import UsersConfig

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'

urlpatterns = [
    path('', include('posts.urls', namespace=PostsConfig.name)),
    path('about/', include('about.urls', namespace=AboutConfig.name)),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace=UsersConfig.name)),
    path('auth/', include('django.contrib.auth.urls')),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),) 

journal/posts/urls.py
from django.urls import path

from posts.apps import PostsConfig
from posts.views import (
    add_comment,
    follow_index,
    group_posts,
    index,
    post_create,
    post_delete,
    post_detail,
    post_edit,
    profile,
    profile_follow,
    profile_unfollow,
)

app_name = PostsConfig.name

urlpatterns = [
    path('', index, name='index'),
    path('create/', post_create, name='post_create'),
    path('group/<slug:slug>/', group_posts, name='group_list'),
    path('posts/<int:post_id>/', post_detail, name='post_detail'),
    path('posts/<post_id>/edit/', post_edit, name='post_edit'),
    path('profile/<str:username>/', profile, name='profile'),
    path('posts/<int:post_id>/comment/', add_comment, name='add_comment'),
    path('follow/', follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        profile_follow,
        name='profile_follow',
    ),
    path(
        'profile/<str:username>/unfollow/',
        profile_unfollow,
        name='profile_unfollow',
    ),
    path('delete/<post_id>/', post_delete, name='post_delete'),
]

journal/users/urls.py
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeDoneView,
    PasswordChangeView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetView,
)
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout',
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login',
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html',
        ),
        name='reset',
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html',
        ),
        name='reset_done',
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html',
        ),
        name='reset_confirm',
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html',
        ),
        name='reset_complete',
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html',
        ),
        name='password_change',
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html',
        ),
        name='password_change_done',
    ),
]

journal/posts/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Post(models.Model):
    text = models.TextField('Текст поста', help_text='Введите текст поста')
    pub_date = models.DateTimeField('Дата публикации', auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='автор',
    )
    group = models.ForeignKey(
        'Group',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='groups',
        verbose_name='группа',
        help_text='Группа, к котрой будет относиться пост',
    )

    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
        null=True,
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self) -> str:
        return self.text[: settings.TEXT_BLOCK]


class Group(models.Model):
    title = models.CharField('название', max_length=200)
    description = models.TextField('описание')
    slug = models.SlugField('slug', max_length=50, unique=True)

    def __str__(self) -> str:
        return self.title[: settings.TEXT_BLOCK_TITLE]


class Comment(models.Model):
    text = models.TextField('Комментарий', help_text='Ваш коментарий')
    pub_date = models.DateTimeField('Дата публикации', auto_now_add=True)
    author = models.ForeignKey(
        User,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='автор комментария',
    )
    post = models.ForeignKey(
        Post,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='комментарий',
    )

    def __str__(self) -> str:
        return self.text[: settings.TEXT_BLOCK]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
    )

    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
    )

    def __str__(self) -> str:
        return self.author[: settings.TEXT_BLOCK_TITLE]

journal/posts/forms.py
from django.forms import ModelForm, TextInput, Textarea

from posts.models import Comment, Post


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        widgets = {
            'text': Textarea(
                attrs={
                    'placeholder': 'Текст поста',
                },
            ),
            'title': TextInput(
                attrs={
                    'placeholder': 'Название группы',
                },
            ),
        }


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        help_texts = {
            'text': 'Текст нового комментария',
        }

journal/posts/views.py
import os

from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.cache import cache
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse

from posts.forms import CommentForm, PostForm
from posts.models import Follow, Group, Post

User = get_user_model()


def index(request):
    post_list = Post.objects.select_related(
        'author', 'group'
    ).prefetch_related('comments')
    paginator = Paginator(post_list, settings.COUNT_ENTRY)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(
        request,
        'posts/index.html',
        context={
            'page_obj': page_obj,
        },
    )


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = group.groups.all()
    paginator = Paginator(post_list, settings.COUNT_ENTRY)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(
        request,
        'posts/group_list.html',
        {
            'page_obj': page_obj,
            'group': group,
        },
    )


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    paginator = Paginator(posts, settings.COUNT_ENTRY)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    follow = False
    if request.user.is_authenticated and request.user != author:
        follow = Follow.objects.filter(
            user=request.user,
            author=author,
        ).exists()

    return render(
        request,
        'posts/profile.html',
        context={
            'page_obj': page_obj,
            'author': author,
            'following': follow,
        },
    )


def post_detail(request, post_id):
    post = get_object_or_404(
        Post.objects.select_related('author', 'group'),
        id=post_id,
    )
    form = CommentForm(request.POST or None)
    if request.user.id == post.author.id:
        return render(
            request,
            'posts/post_detail.html',
            context={
                'post': post,
                'form': form,
                'edit_post': True,
            },
        )

    return render(
        request,
        'posts/post_detail.html',
        context={
            'post': post,
            'form': form,
        },
    )


@login_required
def post_create(request):
    form = PostForm(request.POST, files=request.FILES or None)
    if not form.is_valid():
        return render(request, 'posts/create_post.html', {'form': form})

    post = form.save(commit=False)
    post.author = request.user
    post.save()
    return redirect('posts:profile', post.author)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post,
    )
    if request.user == post.author:
        if form.is_valid():
            form.save()
            return redirect(
                'posts:post_detail',
                post_id,
            )

    return render(
        request,
        'posts/create_post.html',
        {
            'post': post,
            'form': form,
            'is_edit': True,
        },
    )


@login_required
def add_comment(request, post_id):
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = get_object_or_404(Post, id=post_id)
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    post_list = Post.objects.filter(
        author__following__user=request.user,
    ).select_related('author', 'group')
    paginator = Paginator(post_list, settings.COUNT_ENTRY)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(
        request,
        'posts/follow.html',
        context={
            'page_obj': page_obj,
        },
    )


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if request.user != author:
        Follow.objects.get_or_create(user=request.user, author=author)
        return redirect('posts:profile', author)
    return redirect('posts:profile', author)


@login_required
def profile_unfollow(request, username):
    get_object_or_404(
        Follow,
        user=request.user,
        author__username=username,
    ).delete()
    return redirect('posts:profile', username)


@login_required
def post_delete(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.user != post.author:
        return redirect('posts:post_detail', post_id=post_id)
    back_point = request.META.get('HTTP_REFERER')
    post.delete()
    if post.image:
        if os.path.isfile(post.image.path):
            os.remove(post.image.path)
    if (f'posts/{post_id}/') not in back_point:
        cache.clear()
        return redirect(back_point)
    return redirect(
        'posts:profile',
        username=request.user.username,
    )

journal/templates/includes/footer.html
<div class="footer-copyright text-center py-3">
  © {{ year }}. Copyright
  <p>
    <span style="color:Olive">Ya</span>kube
  </p>
</div>

journal/templates/includes/header.html
{% load static %}
<article>
  <link rel="stylesheet" href="{% static 'css/my_style.css' %}">
  <nav class="navbar navbar-light" style="background-color: #00FFFF">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}"
             width="30"
             height="30"
             class="d-inline-block"
             alt="">
        <span style="color:Olive">Ya</span>kube
      </a>
      {% with request.resolver_match.view_name as view_name %}
        <ul class="nav nav-pills">
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'about:author' %}active{% endif %}"
               href="{% url 'about:author' %}">Об авторе</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'about:tech' %}active{% endif %}"
               href="{% url 'about:tech' %}">Технологии</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'about:skill' %}active{% endif %}"
               href="{% url 'about:skill' %}">Тетрис</a>
          </li>
          {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link {% if view_name == 'posts:post_create' %}active{% endif %}"
                 href="{% url 'posts:post_create' %}">Новая запись</a>
            </li>
            <li class="nav-item">
              <a class="nav-link link-light {% if view_name == 'users:reset' %}active{% endif %}"
                 href="{% url 'users:password_change' %}">Изменить пароль</a>
            </li>
            <li class="nav-item">
              <a class="nav-link link-light {% if view_name == 'users:logout' %}active{% endif %}"
                 href="{% url 'users:logout' %}">Выйти</a>
            </li>
            <li>
              <a class="nav-link">Пользователь:{{ user.username }}</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link link-light" href="{% url 'users:login' %}">Войти</a>
            </li>
            <li class="nav-item">
              <a class="nav-link link-light" href="{% url 'users:signup' %}">Регистрация</a>
            </li>
          {% endif %}
        </ul>
      </ul>
    {% endwith %}
  </div>
</nav>
</article>

journal/templates/includes/post.html
{% load thumbnail %}
<div class="container">
  <div class="row">
    <div class="col-4">
      <li>
        Автор: {{ post.author.get_full_name }} -
        <a class="colorDummy color special"
           href="{% url 'posts:profile' post.author %}">#{{ post.author }}</a>
      </li>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2 img-thumbnail" src="{{ im.url }}">
    {% endthumbnail %}

    <li>Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
    <a class="colorDummy color special"
       href="{% url 'posts:post_detail' post.id %}">подробная информация</a>
  </div>
  <div class="col">
    <p>{{ post.text|linebreaksbr|slice:":300" }}</p>
  </div>
  <div class="col-2">
    <button type="button" class="badge text-bg-info position-relative">
      комментариев
      <span class="class=badge rounded-pill text-bg-info">
        {{ post.comments.all.count }}
      </span>
    </button>
    <br>
    {% include "posts/includes/edit_button.html" %}
    <br>
    {% include "posts/includes/delete_button.html" %}
    <br>
  </div>
</div>
</div>